// Generated by demos/tools/build-project-data.mjs — do not edit by hand.
// Run `node demos/tools/build-project-data.mjs` after adding a project.
window.PROJECT_GROUPS = [
  {
    "key": "volumetric",
    "label": "Volumetrics & SDF"
  },
  {
    "key": "physics",
    "label": "Physics & Simulation"
  },
  {
    "key": "generative",
    "label": "Generative Geometry"
  },
  {
    "key": "field",
    "label": "Field & Mathematics"
  },
  {
    "key": "signal",
    "label": "Audio & Signal"
  },
  {
    "key": "tools",
    "label": "Tools & Type"
  },
  {
    "key": "rendering",
    "label": "Rendering & 3D"
  }
];

window.PROJECTS = [
  {
    "slug": "bezier-editor",
    "title": "Bezier Lab — cubic Bézier shape editor",
    "desc": "A cubic Bézier shape editor: drag the four control points, watch the control polygon, fill the result as a real shape.",
    "group": "tools",
    "kb": 47
  },
  {
    "slug": "boolean-3d-csg",
    "title": "Boolean SDF 3D — raymarched constructive solid geometry",
    "desc": "Constructive solid geometry in 3D — union, intersection and difference on signed distance fields, with the operands in motion.",
    "group": "rendering",
    "kb": 38
  },
  {
    "slug": "boolean-sdf-2d",
    "title": "Boolean SDF 2D — animated constructive solid geometry",
    "desc": "Two moving shapes and a boolean operation between them, so you can watch a hole open and close in real time.",
    "group": "field",
    "kb": 43
  },
  {
    "slug": "caustics-pool",
    "title": "Caustics Pool — inverted photon mapping",
    "desc": "The bright web of light that refracted water casts on a pool floor, from analytic Gerstner-wave normals through Snell refraction to focused irradiance.",
    "group": "volumetric",
    "kb": 31
  },
  {
    "slug": "cellular-automata",
    "title": "Rule Lab — cellular automata bench",
    "desc": "A rule bench for Conway’s Life, Langton’s ant and Brian’s Brain, plus a free B/S rule string, drawn as crisp blocks.",
    "group": "physics",
    "kb": 47
  },
  {
    "slug": "chaos-game-ifs",
    "title": "Chaos Game — Iterated Function Systems",
    "desc": "The chaos game for Sierpinski, Koch, Barnsley fern and the dragon curve, density-accumulated so the attractor resolves.",
    "group": "generative",
    "kb": 30
  },
  {
    "slug": "cloth-simulation",
    "title": "Cloth — mass-spring lattice with progressive tearing",
    "desc": "A mass-spring cloth pinned at the corners, grabbable with the mouse, that frays progressively as springs exceed their strain limit.",
    "group": "physics",
    "kb": 44
  },
  {
    "slug": "collatz",
    "title": "Collatz Phase Portrait · 3n+1 basins",
    "desc": "Collatz trajectories as time-series plots, with many starts coloured by fate so the basins of attraction become visible.",
    "group": "field",
    "kb": 43
  },
  {
    "slug": "color-theory",
    "title": "OKLCH Harmony Console",
    "desc": "An OKLab/OKLCH colour wheel with analogous, complementary and triadic harmony built in a perceptual space, plus real contrast ratios.",
    "group": "field",
    "kb": 36
  },
  {
    "slug": "cpu-fluid",
    "title": "CPU Fluid — Navier–Stokes on a staggered grid",
    "desc": "An incompressible fluid solver in plain JavaScript on a 2D canvas — advect, add forces, solve pressure, subtract gradient. No GPU at all.",
    "group": "physics",
    "kb": 36
  },
  {
    "slug": "cpu-raytracer",
    "title": "46 — CPU Path Tracer",
    "desc": "A progressive raytracer written in JavaScript and running in Web Workers. No GPU involved — just spheres, shadows and reflections.",
    "group": "rendering",
    "kb": 35
  },
  {
    "slug": "curve-fitting",
    "title": "Least-Squares Fitting Lab",
    "desc": "Least-squares fits for linear, quadratic, exponential and sine models, with a residual plot and R² beneath each.",
    "group": "field",
    "kb": 44
  },
  {
    "slug": "diffusion-limited",
    "title": "Diffusion-Limited Aggregation · on-lattice DLA",
    "desc": "Random walkers that stick where they touch, growing branching dendritic structures — the same physics as coral and frost.",
    "group": "generative",
    "kb": 47
  },
  {
    "slug": "dispersion-glass",
    "title": "04 · Dispersion Glass",
    "desc": "A refractive glass solid traced three times at a slightly different index per colour channel, so dispersion and coloured fringes are physically real.",
    "group": "volumetric",
    "kb": 28
  },
  {
    "slug": "double-pendulum",
    "title": "Double Pendulum — chaotic Lagrangian dynamics with a live Poincaré section",
    "desc": "A double pendulum with a fading trail, beside a live plot of successive angle pairs so the strange attractor becomes visible.",
    "group": "physics",
    "kb": 55
  },
  {
    "slug": "dsp-filters",
    "title": "DSP Filter Lab — biquad &amp; comb response",
    "desc": "Biquad and comb filters implemented for real, with their magnitude response and the before/after spectrum of a test signal.",
    "group": "signal",
    "kb": 41
  },
  {
    "slug": "exoplanet",
    "title": "EXOPLANET PROCEDURATOR — raymarched FBM world",
    "desc": "A procedural planet from a seed: FBM terrain, biome colour by elevation and latitude, an animated cloud shell, a Fresnel atmosphere, and a real terminator.",
    "group": "volumetric",
    "kb": 48
  },
  {
    "slug": "fourier-drawing",
    "title": "Fourier Drawing — 2-D DFT term reduction",
    "desc": "A discrete Fourier transform keeping only the lowest coefficients — and the image still reads as the original.",
    "group": "field",
    "kb": 43
  },
  {
    "slug": "fractal-flames",
    "title": "Fractal Flames — colour-binned density estimation",
    "desc": "The fractal flame algorithm: affine transforms with colour, a density histogram, and a gamma-correct display.",
    "group": "generative",
    "kb": 45
  },
  {
    "slug": "generative-poster",
    "title": "41 · Generative Poster — modular grid solver",
    "desc": "A parameterised poster system with real compositional rules: alignment, a clear focal point, negative space, restrained palette.",
    "group": "tools",
    "kb": 65
  },
  {
    "slug": "harmonograph",
    "title": "Harmonograph Plotter · Damped Dual Pendulum",
    "desc": "Two orthogonal damped pendulums at related frequencies, traced as a fading path into intricate plotted figures.",
    "group": "field",
    "kb": 42
  },
  {
    "slug": "ising-model",
    "title": "2D Ising Model — Metropolis Monte Carlo",
    "desc": "The 2D Ising model under Metropolis Monte Carlo, plotting magnetisation against temperature so the phase transition becomes visible.",
    "group": "generative",
    "kb": 41
  },
  {
    "slug": "lsystem-flora",
    "title": "L-System Flora — 3D stochastic parametric L-system",
    "desc": "3D L-system turtle grammar growing branching plants, rendered as tapered shaded tubes — trees, ferns and flowers from one algorithm.",
    "group": "generative",
    "kb": 59
  },
  {
    "slug": "mandelbulb",
    "title": "MANDELBULB — escape-time distance estimator",
    "desc": "The Mandelbulb by distance estimation, with orbit-trap colouring that turns the fractal into structured bands rather than a flat blob.",
    "group": "volumetric",
    "kb": 34
  },
  {
    "slug": "marching-cubes",
    "title": "Marching Cubes — isosurface extraction from an animated scalar field",
    "desc": "The real marching cubes algorithm over an animated scalar field, extracting a lit isosurface mesh every frame with flat shading.",
    "group": "generative",
    "kb": 73
  },
  {
    "slug": "menger-sponge",
    "title": "Menger Sponge — raymarched recursion",
    "desc": "A Menger sponge raymarched with correct distance bounds, so the recursion resolves cleanly instead of the march overshooting through it.",
    "group": "volumetric",
    "kb": 19
  },
  {
    "slug": "model-viewer",
    "title": "FIELD / MODEL VIEWER — procedural SDF product render",
    "desc": "A 3D model generated entirely in code, presented like a product render: studio lighting, turntable, soft ground shadow, PBR shading.",
    "group": "rendering",
    "kb": 70
  },
  {
    "slug": "nbody-orbits",
    "title": "N-Body Integrator Bench — Euler vs Verlet vs RK4",
    "desc": "The same star system under forward Euler, velocity Verlet and RK4, with a live energy-drift plot showing which integrator is lying to you.",
    "group": "physics",
    "kb": 50
  },
  {
    "slug": "nebula",
    "title": "Nebula 08 — layered FBM volumetrics",
    "desc": "Layered FBM bands in a deep palette, a bright core, parallax star fields, and god rays raking from an off-screen star.",
    "group": "volumetric",
    "kb": 26
  },
  {
    "slug": "parametric-surfaces",
    "title": "PARAMETRIC SURFACES — Klein · Enneper · Möbius · Trefoil",
    "desc": "Klein bottle, Enneper surface, Möbius strip and trefoil knot, tessellated and lit as rotating 3D meshes.",
    "group": "generative",
    "kb": 36
  },
  {
    "slug": "phase-portrait",
    "title": "Phase Portrait — Attractors, Equilibria, Basins",
    "desc": "Lorenz, van der Pol, Hénon, Clifford and the logistic bifurcation, each traced as a live fading phase portrait.",
    "group": "field",
    "kb": 65
  },
  {
    "slug": "pixel-painter",
    "title": "Pixel Painter — indexed-colour sprite editor",
    "desc": "A small indexed-colour pixel editor: limited palette, pencil and fill, nearest-neighbour zoom, on a generated starting image.",
    "group": "tools",
    "kb": 44
  },
  {
    "slug": "poisson-disc",
    "title": "Point Sampling — uniform · jittered lattice · Poisson-disc",
    "desc": "Three sampling strategies side by side — uniform random, jittered lattice, and Poisson-disc — with a nearest-neighbour metric proving which clumps.",
    "group": "generative",
    "kb": 38
  },
  {
    "slug": "procedural-city",
    "title": "Procedural City — block layout, zoning and a lit night skyline",
    "desc": "A generated city from a road grid with variation, blocks subdivided into lots, and a taller downtown falling away to suburbs.",
    "group": "rendering",
    "kb": 71
  },
  {
    "slug": "quadtree-fractal",
    "title": "Quadtree Fractal — recursive subdivision on a seeded field",
    "desc": "A square subdividing into four wherever seeded noise crosses a threshold, growing level by level.",
    "group": "generative",
    "kb": 32
  },
  {
    "slug": "rigidbody-2d",
    "title": "Rigid Body 2D — impulse solver / SAT manifolds",
    "desc": "An impulse-based 2D physics engine: SAT collision, rotation, friction and restitution, rendered as lit solid shapes rather than wireframes.",
    "group": "physics",
    "kb": 43
  },
  {
    "slug": "sandpile",
    "title": "Sandpile · Bak–Tang–Wiesenfeld",
    "desc": "The Bak–Tang–Wiesenfeld sandpile. Grains accumulate, overloaded cells topple, and branching avalanches spread outward like lightning.",
    "group": "physics",
    "kb": 35
  },
  {
    "slug": "sdf-2d",
    "title": "2D Signed Distance Field Lab — boolean composition, analytic AA",
    "desc": "Compose 2D distance primitives with union, intersection, subtraction and smooth-min, anti-aliased exactly from the distance value.",
    "group": "field",
    "kb": 44
  },
  {
    "slug": "sdf-explorer",
    "title": "SDF EXPLORER — sphere-traced primitive compositor",
    "desc": "Compose organic merged forms from SDF primitives. Add, move, and blend spheres, boxes, tori and capsules with smooth-min, over a soft-shadowed ground plane.",
    "group": "volumetric",
    "kb": 50
  },
  {
    "slug": "sdf-text",
    "title": "Signed Distance Type — text reconstructed from a distance field",
    "desc": "Text rendered from a signed distance field, so it stays crisp at any scale, with the underlying field visible underneath.",
    "group": "tools",
    "kb": 60
  },
  {
    "slug": "shader-lab",
    "title": "Shader Lab — live GLSL playground",
    "desc": "A live fragment-shader editor with presets, uniform sliders, and compile errors shown instead of failing silently.",
    "group": "rendering",
    "kb": 49
  },
  {
    "slug": "spectrogram",
    "title": "Spectrogram · Log-Frequency Audio Waterfall",
    "desc": "A scrolling log-frequency spectrogram waterfall from a real FFT, fed a deterministic synthesised signal so it renders identically offline.",
    "group": "signal",
    "kb": 47
  },
  {
    "slug": "spring-lattice",
    "title": "Structural Spring Lattice — Verlet mass-spring truss",
    "desc": "A 3D structural lattice under load, deforming in real time, with every spring coloured by whether it is stretched or compressed.",
    "group": "physics",
    "kb": 52
  },
  {
    "slug": "synth-lab",
    "title": "SYNTH·LAB — 38 · subtractive synthesis playground",
    "desc": "A subtractive synthesis chain — oscillator, ADSR, resonant filter, output — with the live waveform, spectrum and signal path.",
    "group": "signal",
    "kb": 54
  },
  {
    "slug": "tilemap-generator",
    "title": "43 · Tilemap Generator — 47-blob autotiler",
    "desc": "A top-down tilemap from value noise and cellular smoothing, drawn with 47-tile autotiling so every edge blends correctly.",
    "group": "tools",
    "kb": 50
  },
  {
    "slug": "type-specimen",
    "title": "№ 40 — Type Specimen",
    "desc": "A typography specimen built only from system font stacks — display scale, rhythm, reading measure, and a letterform row.",
    "group": "tools",
    "kb": 39
  },
  {
    "slug": "volumetric-clouds",
    "title": "CUMULUS — raymarched volumetric clouds",
    "desc": "Raymarched volumetric clouds: a 3D density field from domain-warped FBM, lit with Beer–Lambert transmittance and a powder term for the dark edges.",
    "group": "volumetric",
    "kb": 36
  },
  {
    "slug": "wang-tiles",
    "title": "Wang Tiles — procedural tileset + arc-consistency solver",
    "desc": "A procedural tileset with coloured edge sockets, filled by a constraint solver so the result is seamless by construction.",
    "group": "generative",
    "kb": 39
  },
  {
    "slug": "wave-function-collapse",
    "title": "Wave Function Collapse — project 42",
    "desc": "A true WFC solver: lowest-entropy selection, arc-consistency propagation, contradiction backtracking, restart on failure.",
    "group": "tools",
    "kb": 48
  },
  {
    "slug": "wave-interference",
    "title": "WAVE INTERFERENCE — superposition, nodes, standing waves",
    "desc": "Plane and point sources summed into a live field, where interference fringes, nodes and antinodes are plainly visible.",
    "group": "signal",
    "kb": 50
  }
];
